
#ifndef __i386_INTRSTUBS_H_
#define __i386_INTRSTUBS_H_

#define INTR_STUB(v) void intr_handler_stub_##v(void);

/* Create function prototypes for interrupt stubs defined in intrstub.s */
INTR_STUB(0)
INTR_STUB(1)
INTR_STUB(2)
INTR_STUB(3)
INTR_STUB(4)
INTR_STUB(5)
INTR_STUB(6)
INTR_STUB(7)
INTR_STUB(8)
INTR_STUB(9)
INTR_STUB(10)
INTR_STUB(11)
INTR_STUB(12)
INTR_STUB(13)
INTR_STUB(14)
INTR_STUB(15)
INTR_STUB(16)
INTR_STUB(17)
INTR_STUB(18)
INTR_STUB(19)
INTR_STUB(20)
INTR_STUB(21)
INTR_STUB(22)
INTR_STUB(23)
INTR_STUB(24)
INTR_STUB(25)
INTR_STUB(26)
INTR_STUB(27)
INTR_STUB(28)
INTR_STUB(29)
INTR_STUB(30)
INTR_STUB(31)

#endif // #ifndef __i386_INTRSTUBS_H_
